version: '3'
services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: site9db_2
      MYSQL_USER: site9user
      MYSQL_PASSWORD: 140286TakaHiro
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./custom.cnf:/etc/mysql/conf.d/custom.cnf

  web:
    build: .
    command: python app.py
    volumes:
      - .:/site9
    #ports:
      #- "5000:5000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- ./static:/static
      - .:/site9
    ports:
      - "8009:7002"
    depends_on:
      - web

volumes:
  db_data:
